기존에 build시에 종종 querydsl이 q클래스를 생성못하는 문제 해결2
6) Attempt to recreate a file for type ... 에러

Querydsl의 Q클래스가 기존에 빌드된 파일과 충돌할 때 발생한다.
즉, Querydsl이 생성하는 클래스가 중복으로 생성되는 문제
public abstract class BaseTimeEntity { ..  여기서 문제가 발생  querydsl이 이 클래스를 Q클래스로 생성할 필요가 없는데 QBaseTimeEntity가 중복 생성되는것으로 보임.
과거에 querydsl이 제대로 동작하지 않았기 때문에 QBaseTimeEntity가 남아있어서 문제없이 쓰였다가 querydsl이 제대로 동작하면서 중복생성
@QueryExclude로 querydsl대상에서 완전히 제외하는방법을 시도

7) @QueryExclude를 했을때 BasetimeEntity가 동작을 못하는건 아닌가

@QueryExclude를 해도 JPA의 Auditing기능은 전혀 영향을 받지 않는다.

8) 그래도 동일한 증상 발생
@QueryExclude를 했는데도 중복 생성되는 문제가 발생하는건 Gradle Querydsl플러그인과 querydsl의 annotationProcessor와 겹쳐 작동하면서 중복 생성하는것으로 보임 따라서 플러그인 설정을 주석처리함.
- plugins{  id "com.ewerk.gradle.plugins.querydsl" version "1.0.10"}
- querydsl {  ... } 주석처리 (플러그인설정)
- compileQuerydsl{...} 주석처리
- configurations { querydsl.extendsfrom compileclasspath} 주석처리
-
tasks.withType(JavaCompile) {
    options.annotationProcessorGeneratedSourcesDirectory = file(querydslDir)
}  이렇게 추가

9) annotationProcessorGeneratedSourcesDirectory' is deprecated
위에서 tasks.withType(javacompile) 하고 options.annotationProcessorGener.. 를 썻는데  gradle 8.0 이후로 deprecated되었다.
최신설정으로 변경
tasks.withType(JavaCompile).configureEach {
    options.generatedSourceOutputDirectory = file(querydslDir)
}

10) Could not get unknown property 'querydslDir' for task ':compileJava' of type org.gradle.api.tasks.compile.JavaCompile.

기존의 querydslDir이 하단에 위치에 있었는데 task.withType(Javacompile)블록에서 querydslDir를 찾는데 하단에있어서 못찾는것 task.withType() 상단으로 올려줌.

11) error: cannot find symbol
        return QItem.item.regTime.after(dateTime);
                         ^
  symbol:   variable regTime
  location: variable item of type QItem

왜일까 @QueryExclude도 해주었는데 중복생성 안되니 되어야 하는데 이번엔 인식을 못한다.

이유는 Querydsl이 Q클래스가 생성될때 상속된 필드를 인식하지 못하기 때문.
Querydsl에서 부모 클래스(BaseTimeEntity)의 필드(regTime)가 Q클래스에서 생성되지 않은 상태이기 때문(BaseTimeEntity 참조)

왜 regTime 필드를 못찾을까?

- BaseTimeEntity에 명시된 필드(regTime)가 Querydsl Q클래스에 없어서 발생
- @MappedSuperclass 클래스의 필드는 기본적으로 Querydsl이 Q클래스로 자동 생성해주지 않습니다.
- 부모 클래스(BaseTimeEntity)가 명시적으로 Querydsl의 대상이 아니기 때문입니다.

-> @QuerySupertype 추가 ,@QueryExclude제거
Querydsl이 부모 클래스의 필드를 반드시 인식할수 있도록 한다.